### PR TITLE
Bump dub to v1.31.1

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Comment by Geod24** [comment]
There's also https://github.com/atilaneves/reggae/blob/master/dub.json#L16
Which is interesting, why the `==` dependency @atilaneves ?

**Comment by kinke** [comment]
Oh right. But goddammit, more things to fix (`std.sumtype` invariant...), and I really don't want to waste any time for such a trivial bump. We also hit a new assertion wrt. the new packages build cache directory.

**Comment by atilaneves** [comment]
> There's also https://github.com/atilaneves/reggae/blob/master/dub.json#L16 Which is interesting, why the `==` dependency @atilaneves ?

No idea.

**Comment by kinke** [comment]
Almost working now; hitting long-path regressions on Windows for the dub-generated `dub_test_root.d` file, where the new `cache` directory comes into play. E.g., 262 chars (limit is 260):
```
D:\a\reggae\reggae\tmp\unit-threaded\XXZRZBa02536\__dub_cache__\dub_depends_on_prebuild\~master\code\dub_depends_on_prebuild-test-application-debug-windows-x86_64-dmd_v2.100.0-dirty-6E340B9CFFB37A989CA544E6BB780A2C78901D3FB33738768511A30617AFA01D\dub_test_root.d
```
This full 64-chars build hash already claims ~25% of the max length.

**Comment by Geod24** [comment]
We have a fix in master, I can just backport this if you'd like ?

**Comment by kinke** [comment]
Oh cool, looking very much forward to https://github.com/dlang/dub/pull/2589. - Yeah, I've worked around the CI problem now. 

I've also pushed an unrelated commit (https://github.com/atilaneves/reggae/pull/180/commits/c2cbf0d7789dc8ca98fa1d230747bde22b435d65), which I hope fixes the long-path issues for some SIL plugins on Windows - where I've had to stick to dub for now. I've tested this reggae build with a few SIL subprojects (REPL, lang, a plugin); all working.

**Review by atilaneves — APPROVED** [review]

**Pull request merged**
