### PR TITLE
no more builtin .sort

### PR DESCRIPTION
**Pull request by John-Colvin**
and if you compiled with warnings you'd have spotted this :-p

### CODE REVIEW

**Comment by atilaneves** [comment]
The unit test build is broken

**Comment by John-Colvin** [comment]
I presume you wouldn't consider making shouldEqual try and call std.algorithm.equal if it gets two ranges? It's quite common to want to test the values of a range against a different range type, like in this pull request, or e.g.
```
iota(10).map!"a*2".filter!"a%3"
    .shouldEqual(only(2, 4, 8, 10, 14, 16));
```

**Comment by atilaneves** [comment]
Actually the version in the Phobos PR already works seamlessly with ranges; it's just hard to backport so I haven't bothered. I'm also on holiday right now so won't have time to look into it until late in the week.

**Comment by atilaneves** [comment]
So, either I update unit-threaded to take ranges, or  this PR could call `.array` after `.sort()`, I think the latter is easier.

**Comment by atilaneves** [comment]
Closed due to [this commit](https://github.com/atilaneves/reggae/commit/58bd61967834cc4da0fe44be7e08c74b492bfb06)

**Pull request closed without merging**
