### PR TITLE
Ninja: Support spaces in flags and paths

### PR DESCRIPTION
**Pull request by kinke**
Mainly for Windows of course.

~~Depends on (and hence currently includes) #122 and #123.~~

### CODE REVIEW

**Comment by atilaneves** [comment]
Rebase? Or just undraft this?

**Comment by kinke** [comment]
I've also checked the .dep files more thoroughly here on my box; they don't work correctly yet for paths with spaces, and quickly testing escaping a space as '\ ' doesn't seem to work either...

**Comment by atilaneves** [comment]
> I've also checked the .dep files more thoroughly here on my box; they don't work correctly yet for paths with spaces, and quickly testing escaping a space as '\ ' doesn't seem to work either...

Does that mean this PR is not enough?

**Comment by kinke** [comment]
For my little test project, it means too many modules are recompiled when a file changes.

**Comment by atilaneves** [comment]
Should this be merged as-is now then?

**Comment by kinke** [comment]
Yep please do (as this fixes the builds at least), I'll try to follow up wrt. dep files.

**Pull request merged**
